---
- name: "junos: run configure trunk port using network_cli"
  junos_command:
    commands:
      - config
      - "delete interfaces {{ port_name }}"
      - "set interfaces {{ port_name }} unit 0 family ethernet-switching interface-mode trunk"
      - "set interfaces {{ port_name }} native-vlan {{ _vlan_id }}"
      - "set interfaces {{ port_name }} unit 0 family ethernet-switching vlan members [{{ _vlan_id }}{% for vlan in trunked_vlans %} {{ vlan }}{% endfor %}]"
      - commit
  register: result
  retries: 10
  delay: 5
  until: result.rc is defined and result.rc == 0
  connection: network_cli
