---
- name: "junos: run update access port using network_cli"
  junos_command:
    commands:
      - config
      - "delete interfaces {{ port }}"
      - "set interfaces {{ port }} unit 0 family ethernet-switching interface-mode access"
      - "set interfaces {{ port }} unit 0 family ethernet-switching vlan members {{ _vlan_id }}"
      - commit
  connection: network_cli
