---
- name: "junos: run create vlan using network_cli"
  junos_command:
    commands:
      - config
      - "set vlans {{ _vlan_name }} vlan-id {{ _vlan_id }}"
      - commit
  register: result
  retries: {{ _retries }}
  delay: {{ _delay }}
  until: result.msg is not defined or result.msg.find('configuration database locked by:') == -1
  connection: network_cli
