---
- name: "junos: run create vlan using network_cli"
  junos_command:
    commands:
      - config
      - "set vlans {{ vlan_name }} vlan-id {{ vlan_id }}"
      - commit
  connection: network_cli
