---
- name: "junos: run create vlan using network_cli"
  junos_command:
    commands:
      - config
      - "set vlans {{ _vlan_name }} vlan-id {{ _vlan_id }}"
      - commit
  register: result
  retries: 10
  delay: 5
  until: result.rc is defined and result.rc == 0
  connection: network_cli
