---
- name: "junos: run create vlan using network_cli"
  junos_command:
    commands:
      - config
      - "set vlans {{ _vlan_name }} vlan-id {{ _vlan_id }}"
      - commit
  connection: network_cli
