---
- name: "junos: run delete vlan using network_cli"
  junos_command:
    commands:
      - config
      - "delete vlans {{ _vlan_name }}"
      - commit
  register: result
  retries: {{ _retries }}
  delay: {{ _delay }}
  until: result.msg is not defined or result.msg.find('configuration database locked by:') == -1
  connection: network_cli
