---
- name: "cumulus: get interfaces"
  nclu:
    commands: "show interface {{ port }} json"
  register: output

- name: "cumulus: set port facts"
  set_fact:
    interface: "{{ output.msg }}"

- name: "cumulus: verify port exists"
  fail:
    msg: "port {{ port }} does not exist on this device"
  when: interface.mode == 'NotConfigured'

- name: "cumulus: remove port configuration"
  nclu:
    commands: "del interface {{ port }}"
    commit: true

- name: "cumulus: administratively disable the port"
  nclu:
    commands: "add interface {{ port }} link down"
    commit: true
