---
- name: "cumulus: configure access port using nclu"
  block:
    - name: "cumulus: reset interface to defaults"
      nclu:
        commands: "del interface {{ port }}"
        commit: true

    - name: "cumulus: build port configuration"
      nclu:
        commands:
          - "add interface {{ port }} bridge access {{ vlanid }}"
          - "del interface {{ port }} link down"
        commit: true
