---
# delegate task to localhost to avoid starting the device connection
- name: "check for required fact: port_name"
  fail:
    msg: "missing required fact: port_name"
  when: not port_name
  delegate_to: localhost

# delegate task to localhost to avoid starting the device connection
- name: "check for required fact: port_description"
  fail:
    msg: "missing required fact: port_description"
  when: not port_description
  delegate_to: localhost

- name: include and run device provider specific tasks
  include_tasks: run.yaml
  vars:
    network_action: conf_trunk_port
