---
# delegate task to localhost to avoid starting the device connection
- name: "check for required fact segmentation_id"
  fail:
    msg: "missing required fact: segmentation_id"
  when: not ml2_segmentation_id
  delegate_to: localhost

- name: include and run device provider specific tasks
  include_tasks: run.yaml ml2_resource='delete_network'
