---
- name: "nxos: remove port configuration"
  nxos_config:
    lines: "default interface {{ ml2_port_name }}"

- name: "nxos: administratively disable the port"
  nxos_config:
    lines: "shutdown"
    parents: ["interface {{ ml2_port_name }}"]
