- project-template:
    name: networking-ansible-tempest-jobs
    check:
      jobs:
        #        - networking-ansible-tempest-ovs
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-networking-ansible:
            voting: false

    gate:
      jobs:
        - networking-ansible-tempest-ovs

- project:
    templates:
      - networking-ansible-tempest-jobs
