- hosts: all
  name: Copy ssh keys from too ~stack
  tasks:
    - shell:
        cmd: |
          set -e
          set -x

          sudo mkdir -p ~stack/.ssh
          sudo cp ~root/.ssh/id_rsa.pub ~root/.ssh/id_rsa ~stack/.ssh
          sudo chmod 700 ~stack/.ssh
          sudo chown -R stack ~stack
        executable: /bin/bash

- hosts: all
  name: fix bridge creation for vxlan connectivity
  tasks:
    - name: create OVS bridges
      command: "ovs-vsctl --may-exist add-br {{ item }}"
      become: yes
      with_items:
        - br_ironic_vxlan
        - "{{ lookup('env', 'OVS_PHYSICAL_BRIDGE') }}"
